# Quarkus Failed to Bind Reproducer

A reproducer for `Failed to bind` exception when running tests.

Used in issue [quarkusio/quarkus#41171](https://github.com/quarkusio/quarkus/discussions/41171).

## Steps to reproduce

This repository is 99% sample code generated by the command:

```shell
mvn io.quarkus.platform:quarkus-maven-plugin:3.11.1:create -DprojectGroupId=org.acme -DprojectArtifactId=google-cloud-functions -Dextensions='google-cloud-functions'
```

After generating the sample code, a dependency was added to the `pom.xml` file.

```xml
<dependency>
  <groupId>io.quarkus</groupId>
  <artifactId>quarkus-rest-jackson</artifactId>
</dependency>
```

1. Clone the repository and run the sample tests:

```shell
./mvnw clean test
```

2. You would see the exceptions for each test executed:

```log
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 2.462 s <<< FAILURE! -- in org.acme.googlecloudfunctions.HelloWorldCloudEventsFunctionTest
[ERROR] org.acme.googlecloudfunctions.HelloWorldCloudEventsFunctionTest.testAccept -- Time elapsed: 0.001 s <<< ERROR!
org.junit.jupiter.api.extension.TestInstantiationException: Failed to create test instance
        at io.quarkus.test.junit.QuarkusTestExtension.initTestState(QuarkusTestExtension.java:788)
        at io.quarkus.test.junit.QuarkusTestExtension.interceptTestClassConstructor(QuarkusTestExtension.java:754)
        at java.base/java.util.Optional.orElseGet(Optional.java:364)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: java.lang.RuntimeException: java.io.IOException: Failed to bind to 0.0.0.0/0.0.0.0:8081
        at io.quarkus.google.cloud.functions.test.CloudFunctionTestResource.inject(CloudFunctionTestResource.java:40)
        at io.quarkus.test.common.TestResourceManager.inject(TestResourceManager.java:166)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at io.quarkus.test.junit.QuarkusTestExtension.createActualTestInstance(QuarkusTestExtension.java:799)
        at io.quarkus.test.junit.QuarkusTestExtension.initTestState(QuarkusTestExtension.java:782)
        ... 4 more
Caused by: java.io.IOException: Failed to bind to 0.0.0.0/0.0.0.0:8081
        at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:349)
        at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:310)
        at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80)
        at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:234)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
        at org.eclipse.jetty.server.Server.doStart(Server.java:401)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
        at com.google.cloud.functions.invoker.runner.Invoker.startServer(Invoker.java:324)
        at com.google.cloud.functions.invoker.runner.Invoker.startTestServer(Invoker.java:276)
        at io.quarkus.google.cloud.functions.test.CloudFunctionsInvoker.start(CloudFunctionsInvoker.java:26)
        at io.quarkus.google.cloud.functions.test.CloudFunctionTestResource.inject(CloudFunctionTestResource.java:38)
        ... 8 more
Caused by: java.net.BindException: Address already in use
        at java.base/sun.nio.ch.Net.bind0(Native Method)
        at java.base/sun.nio.ch.Net.bind(Net.java:555)
        at java.base/sun.nio.ch.ServerSocketChannelImpl.netBind(ServerSocketChannelImpl.java:337)
        at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:294)
        at java.base/sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:89)
        at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:344)
        ... 18 more
```

3. Some stuff that I could verify are:

   - Transitive dependency `quarkus-vertx-http` of `quarkus-rest-jackson` seems to be causing the issue.

   - Using a random test port doesn't prevent the exceptions.

   - The JAR still can be built and executed without any issues (using `./mvnw clean package -DskipTests=true`).
